language: ruby
rvm:
  - 2.2.5
install:
  - source travis/texlive/install
  - tlmgr install dvisvgm
before_script:
  - ./travis/gitbot/clone
script:
  - bundle install
  - bundle exec jekyll build
after_script:
  - ./travis/gitbot/push
branches:
  only:
  - jekyll
