language: ruby
install:
  - source travis/texlive/install
before_script:
  - ./travis/gitbot/clone
script:
  - bundle install
  - bundle exec jekyll build
after_script:
  - ./travis/gitbot/push
branches:
  only:
  - gh-pages-source
