language: ruby
rvm:
  - 2.2.5
install:
  - source texlive/install
before_script:
  - ./travis/gitbot/clone
script:
  - bundle install
  - bundle exec jekyll build
after_script:
  - ./travis/gitbot/push
branches:
  only:
  - jekyll
