language: ruby
rvm:
  - 2.2.5
install:
  - source travis/texlive/install
before_script:
  - ./travis/gitbot/clone
script:
  - echo '\documentclass{article}\begin{document}Hello world.\end{document}' > foo.tex
  - latexmk foo.tex
  - bundle install
  - bundle exec jekyll build
after_script:
  - ./travis/gitbot/push
branches:
  only:
  - jekyll
