env:
  CODECLIMATE_REPO_TOKEN: 1234
language: ruby
rvm:
  - 2.3
install:
  - source travis/texlive/install
  - bundle install
before_script:
script:
  - bundle exec rspec
branches:
  only:
  - master
