name: 'Setup TeX Live'
description: 'Setup TeX Live'
inputs:
  version:
    required: false
    default: '2.7'
  cache-key:
    required: false
    default: gems-
outputs: {}
runs:
    using: "composite"
    steps:

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.version }}

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ inputs.cache-key }}-${{ hashFiles('Gemfile', 'jekyll-antex.gemspec') }}
          restore-keys: ${{ inputs.cache-key }}-

      - name: Install Ruby gems
        shell: bash
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
