#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

cd $TRAVIS_BUILD_DIR
source travis/config

# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
# if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    # echo "Skipping deploy; just doing a build."
    # doCompile
    # exit 0
# fi

git clone https://github.com/$TRAVIS_REPO_SLUG.git $GIT_TARGET_FOLDER
cd $GIT_TARGET_FOLDER
git checkout $GIT_TARGET_BRANCH || git checkout --orphan $GIT_TARGET_BRANCH
git rm -rf .
