#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails
set -e

SOURCE_BRANCH="jekyll"
TARGET_BRANCH="gh-pages"

# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    echo "Skipping deploy; just doing a build."
    doCompile
    exit 0
fi

# Save some useful information
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\/git@github.com:}
SHA=`git rev-parse --verify HEAD`

# Clone the existing gh-pages for this repo into out/
# Create a new empty branch if gh-pages doesn't exist yet (should only happen on first deploy)
git clone $REPO output
cd output
git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
find . ! -name '.git' -type d -o -type f -exec rm -rvf {} +
cd ..

# Clean out existing contents
# rm -rf output/**/* || exit 0
