#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

export GITBOT_USER_NAME="Paolo Brasolin (Travis CI)"
export GITBOT_USER_EMAIL="paolo.brasolin@gmail.com"
export GITBOT_SOURCE_BRANCH=jekyll
export GITBOT_TARGET_BRANCH=gh-pages
export GITBOT_TARGET_FOLDER=_site
# export GITBOT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

