#!/usr/bin/env bash

#===[ Load configuration. ]=====================================================

GITBOT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck source=config
source "$GITBOT_ROOT/config"

#===[ Decrypt private key and add to keyring. ]=================================

openssl aes-256-cbc \
  -K "${encrypted_ae212afd130a_key:?}" \
  -iv "${encrypted_ae212afd130a_iv:?}" \
  -in "$GITBOT_ROOT/deploy_key.enc" \
  -out "$GITBOT_ROOT/deploy_key" \
  -d

chmod 600 "$GITBOT_ROOT/deploy_key"
eval "$(ssh-agent -s)"
ssh-add "$GITBOT_ROOT/deploy_key"
rm "$GITBOT_ROOT/deploy_key"

#===[ Configure git. ]==========================================================

cd "$TRAVIS_BUILD_DIR/$GITBOT_TARGET_FOLDER" || exit 1

git config user.name "$GITBOT_USER_NAME"
git config user.email "$GITBOT_USER_EMAIL"
git config push.default simple

#===[ Safety check. ]===========================================================

# If there are no changes to the compiled out
# (e.g. this is a README update) then just bail.
# if [ -z `git diff --exit-code` ]; then
    # echo "No changes to the output on this push; exiting."
    # exit 0
# fi

#===[ Do push. ]================================================================

git add -A
git commit -m "Travis #$TRAVIS_BUILD_NUMBER"
git push "git@github.com:$TRAVIS_REPO_SLUG.git" "$GITBOT_TARGET_BRANCH"

